
# https://docs.netlify.com/configure-builds/file-based-configuration
[build]
  publish = "./public"
  command = "yarn build"

[context.production]
  environment = {REACT_APP_API_URL = "https://react-pizza-store.netlify.app/" }

[context.deploy-preview]
  environment = {REACT_APP_API_URL = "https://react-pizza-store.netlify.app/" }

[context.branch-deploy]
  environment = {REACT_APP_API_URL = "https://react-pizza-store.netlify.app/" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Define which paths this specific [[headers]] block will cover.
[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "*"
    Access-Control-Allow-Headers = "*"